### PR TITLE
Expose autoCommit and other missing config in types

### PR DESCRIPTION
**Pull request by nicolaslt**
This is a draft as the version updates would require #2 to be merged first.

I was particularly looking for disabling `autoCommit`.

~I then learned about the `Arg1` trick and realised there is no need to re-define those types.
It hinders readability a bit though, so I'm not opposed to reverting to the first commit on this PR.~ TS compiler was not happy, and I don't really understand why. Problem for another time.

### CODE REVIEW

**Comment by ivank** [comment]
I'd prefer to reuse `AvroConsumerRun` types as those inherit kafkajs types with all of their configs. Eventually when we figure out what exactly are the different use cases for this we could use our own types and not expose any of the "implementation details" but for now I'm honestly not sure which configs are actually useful so I've opted just to expose all of them. And the one place I've opted to not do that ended up being needed :)

The code is essentially "put the configs for `consumer`,`subscribe` and `run` into one for ease of use. We could express that - have 3 types for each of those and have one `CastleConsumerConfig` which would either be:

```typescript
export interface CastleConsumerConfig<T = any>
  extends ConsumerConfig,
    CastleConsumerRun<T>,
    CastleTopicSubscribe {}
```
Or
```typescript
export type CastleConsumerConfig<T = any> = ConsumerConfig &
  CastleConsumerRun<T> &
  CastleTopicSubscribe;
```

Depending on which one looks better when actually used. 

What do you think?

**Comment by nicolaslt** [comment]
I agree that for now it's probably wiser to expose all of kafkajs+avro-kafkajs configurations. We can always re-wrap castle itself when we need to (I did that for my team in a closed source repo).

I did attempt to not needing to copy/paste the types manually (see [that commit](https://github.com/ovotech/castle/commit/c3226631bf9bcedfe3dd9b14fc78722780b1326c) , but kafkajs not exposing their type definition for those functions makes it a bit hard (and Arg1 didn't seem to play well witt type combinations)

**Comment by ivank** [comment]
yeah but we can use the type from avro-kafkajs for now, and do a pr to kafkajs itself maybe :)

**Comment by nicolaslt** [comment]
Fear enough, I'll make the changes.

**Comment by nicolaslt** [comment]
I took a look this morning, it seems like the PR already was more or less what you had in mind. But I made it cleaner anyway. :-)

I'll go make a PR in kafkajs now though

**Comment by nicolaslt** [comment]
There we go: https://github.com/tulios/kafkajs/pull/615

**Comment by ivank** [comment]
Huh they've merged the PR, we could also update this one to take advantage of it :)

**Comment by nicolaslt** [comment]
Yeah, it's not released yet though. I'd rather we merge and release our
side than start to ask for releases on kafkajs.

Best case scenario when the kafkajs PR is released: the types aren't
changed and it's just an internal type reshuffle for us so we won't need to
change the version.

Worst case scenario: they have more options in their release, in which case
we should up the version our side anyway.

**Pull request merged**
