### PR TITLE
Update snapshots to fix tests

### LINKED ISSUE #142: avro-ts: Publish a new NPM release
I'm looking to use the capabilities added in the PR https://github.com/ovotech/castle/pull/139, but see that a new NPM package has not been published.

Can you please make a new release with the latest changes available?

### PR DESCRIPTION
**Pull request by AlexeyRaga**
## Changes

- Update existing snapshots to include Avro Schemas
- This fixes failing tests after #139 
- Closes #142

### CODE REVIEW

**Comment by AlexeyRaga** [comment]
@ivank This should fix failing tests. Could you please have a look and let us know if there is anything else that needs to be done?

**Comment by AlexeyRaga** [comment]
@ivank ping! :)

**Comment by ivank** [comment]
No longer part of OVO so don't have rights to merge - sorry :( @phayzor maybe you can help the process along?

**Comment by AlexeyRaga** [comment]
@phayzor will you be able to review and merge this fix please?

**Comment by AlexeyRaga** [comment]
Ping, anyone?

**Comment by SCdF** [comment]
@AlexeyRaga apologies for the immense delay :-)

I've merged your PR, and new minor versions of both `avro-ts` and `avro-ts-cli` have been published. Let me know if you have any issues.

Apart from those two packages, castle is no longer an actively maintained project, as its feature set is now covered by kafkajs. I'm just sorting out some permission issues, but over the next few weeks I'll be archiving this repo, with an explanation as to how you can achieve what castle does without it. I'll also be moving `avro-ts` and `avro-ts-cli` into a separate, maintained repo.

Again, apologies it took so long to get your PR merged.

**Pull request merged**
